### PR TITLE
Fix develop

### PR DESCRIPTION
**Pull request by ellisjoe**

### CODE REVIEW

**Comment by uschi2000** [comment]
https://eng.uber.com/research/keeping-master-green-at-scale/

**Comment by uschi2000** [comment]
but the root cause is the same, right? (CI against an outdated develop branch)

**Comment by ellisjoe** [comment]
well yeah, it's just that in our case there was no cost to the failed build, in their case devs can't do work

**Comment by ellisjoe** [comment]
lol I don't think we have the same problem here: `concurrently committing code changes by thousands of engineers to a big repository, with millions of lines of code`

**Pull request merged**
