### PR TITLE
Instrument client TLS handshakes

### PR DESCRIPTION
**Pull request by carterkozak**
==COMMIT_MSG==
Instrument client TLS handshakes
==COMMIT_MSG==

### CODE REVIEW

**Comment by carterkozak** [comment]
@ferozco I can't seem to add you as a reviewer on this, not sure what's going on!

**Comment by iamdanfox** [comment]
I think all the graphs we have at the moment assume that these connections are only instrumented on the server-side - can we differentiate the client & server side in the metric names somehow?

Also if these just say `tls.handshake` then in our birds-eye graphs we might end up double-counting requests that come from dialogue clients?

**Comment by carterkozak** [comment]
The server produces metrics tagged `context: server`, CJR already provides these from the client side:
https://github.com/palantir/conjure-java-runtime/pull/1446

**Review by iamdanfox — APPROVED** [review]
Ah great, ok I see we'd get a `context: gatekeeperservice` tag in DD.

**Pull request merged**
