### PR TITLE
Add dialogue-java-client

### PR DESCRIPTION
**Pull request by uschi2000**

### CODE REVIEW

**Comment by uschi2000** [comment]
FYI, @ellisjoe @markelliot , this adds a Java11 client to Dialogue. I refactored this repo a fair amount to match conjure-undertow in terms of how serialization works (https://github.com/palantir/dialogue/pull/30 ) and on the way removed the okhttp coupling. This PR isn't quite done, but it should be easy enough.

**Comment by ellisjoe** [comment]
What's the plan for how things like backoff, retry, blacklisting, limiting, etc are going to work here?

**Comment by uschi2000** [comment]
There's no concrete plan.

**Comment by ellisjoe** [comment]
Alright. I feel like that's where the interesting stuff is? Most of the issues we have today are less related to okhttp and more related to that logic.

All for using the java http client though.

**Pull request merged**
